import { getServerSession } from "next-auth";
import LoginBtn from "./LoginBtn";
import LogOutBtn from "./LogoutBtn";
import "./globals.css";
import Link from "next/link";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//웹페이지 전 주소에 적용되는 레이아웃
export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/knowledgeai" className="logo">
            지식 AI IN
          </Link>
          <Link href="/write" prefetch={false}>
            글작성
          </Link>

          {session ? (
            <span>
              {session.user.name} <LogOutBtn></LogOutBtn>{" "}
            </span>
          ) : (
            <LoginBtn></LoginBtn>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
